name: MoodHub CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./MoodHub/Frontend

      - name: Lint frontend
        run: npm run lint
        working-directory: ./MoodHub/Frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./MoodHub/Frontend

      - name: Install backend dependencies
        run: npm ci
        working-directory: ./MoodHub/Backend